name: test-codebuild-runner

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on:
      - codebuild-simple-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Print basic info
        run: |
          echo "Hello from CodeBuild-hosted runner"
          echo "Run ID: ${{ github.run_id }}"
